export const CATEGORIES = [
  { id: 'technology', displayName: 'Technology' },
  { id: 'lifestyle', displayName: 'Lifestyle' },
  { id: 'travel', displayName: 'Travel' },
  { id: 'health-wellness', displayName: 'Health & Wellness' },
  { id: 'food-recipes', displayName: 'Food & Recipes' },
  { id: 'personal-development', displayName: 'Personal Development' },
  { id: 'finance-investment', displayName: 'Finance & Investment' },
  { id: 'education', displayName: 'Education' },
  { id: 'entertainment', displayName: 'Entertainment' },
  { id: 'fashion-beauty', displayName: 'Fashion & Beauty' },
  { id: 'career-employment', displayName: 'Career & Employment' },
  { id: 'sports-fitness', displayName: 'Sports & Fitness' },
  { id: 'parenting-family', displayName: 'Parenting & Family' },
  {
    id: 'environment-sustainability',
    displayName: 'Environment & Sustainability',
  },
  { id: 'art-culture', displayName: 'Art & Culture' },
];
